### ISSUE TITLE
Feature Request: Config option for stealth level that is considered invisible

### ISSUE THREAD

**Issue by Silvertide7** [Jackiecrazy/CloakAndDagger#10]
I'd like to be able to customize what stealth level is considered being invisible. I want to make some armors that increase stealth and some that reduce it, and the player would have to reach a certain stealth level, say positive 10, to be considered invisible. Right now running around without armor (0 Stealth) is considered invisible and I'd like to make it so that the player should is still seen okay with no armor. They have to invest and make choices in armor that increases their stealth if they want to be able to sneak around. A config option of what stealth level is considered invisible would allow that.

**Comment by Jackiecrazy** [comment]
set the player's base stealth to a negative value with an attribute command and adjust armor attributizer values accordingly. Stealth should only become positive under exceptional circumstances, because every point of positive stealth is intentionally incredibly powerful. 10 stealth means you can remain within clear sight in broad daylight without arousing suspicion.
I do not cancel invisibility not rendering you, I only cancel armor rendering when invisible and above a stealth threshold, and change armor coverage percentage from 25% per piece to 5% per negative stealth. Being seen with no armor thus makes no sense as there is nothing to render.

**Comment by Silvertide7** [comment]
Ah okay, I'll need to play around with the system a little more and I'll
try that attribute command as well. Thank you for the info! I just noticed
even when I'm not invisible and standing upright mobs don't seem to notice
me when I'm not wearing armor. Id just like to temper that back a little
bit so players aren't very stealthy until they invest in armor that makes
them stealthy. Gives an interesting alternative to just always wearing the
most armor piece they can.

**Comment by Jackiecrazy** [comment]
This is the expected behavior at 0 stealth. To change that, set the base stealth value lower.
The entire C&D is made to provide said interesting alternative. When you're not wearing anything, aside from being extremely stealthy, you also lose out on survivability and armor enchantments (protection IV is still the single most broken form of damage mitigation). It takes far less investment to acquire a set of enchanted "light" armor than it does to go all-in on running around naked. Regardless, it is your choice what you do with your game.

**Comment by Silvertide7** [comment]
Sounds good, yeah I'll customize mine with the attribute command and see how it goes. Thanks for the help!
