### ISSUE TITLE
Minecraft Crashes almost immediately when forge starts loading mods. 1.20.1

### ISSUE THREAD

**Issue by Lstriker8D8** [Jackiecrazy/CloakAndDagger#11]
Minecraft crashes as stated above. I tested all of the versions for 1.20.1 released so far and they all caused it to crash the same way. Tried removing zombie awareness since that was the only mod i could think of that i have that would cause a conflict and no luck. I'll link the crash report as well. 
[latest.log](https://github.com/Jackiecrazy/CloakAndDagger/files/13932725/latest.log)

**Comment by Jackiecrazy** [comment]
Magnesium breaks the dependency loading screen so it'll immediately crash instead of showing you which mod you didn't install, which is technically faster but leads to situations like this if you don't scour the logs.
`Mod ID: 'footwork', Requested by: 'cloakanddagger', Expected range: '[2.0,)', Actual version: '[MISSING]'`
